# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: community
name: osbuild
version: 0.1.0
readme: README.md
authors:
  - Chris Keller (github.com/nasx)
  - Andrew Block (github.com/sabre1041)
  - Chad Ferman (github.com/@chadmf)
  - Jordi Gil (github.com/jordigilh)
  - Ygal Blum (github.com/ygalblum)
  - Andrew Ae (github.com/andrewWithTheRedHat)
  - Adam Miller (github.com/maxamillion)
description:  Deploy the osbuild service and 
license_file:
  - licenses/APACHE2.0-LICENSE.txt
  - licenses/GPLv3+-LICENSE.txt
tags:
# tags so people can search for collections https://galaxy.ansible.com/search
# tags are all lower-case, no spaces, no dashes.
  - osbuild 
  - osbuilder
  - imagebuild 
  - imagebuilder
  - rhel4edge
  - edge
  - rpmostree
repository: https://github.com/ansible-collections/community.osbuild
#documentation: https://github.com/ansible-collection-migration/community.REPO_NAME/tree/main/docs
homepage: https://github.com/ansible-collections/community.osbuild
issues: https://github.com/ansible-collections/community.osbuild/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
