- name: Generate In-Memory Inventory of OpenShift VMs
  hosts: localhost
  roles:
    - role: openshift-image-builder-imi
      tags: openshift-image-builder-imi

- name: Configure Image Builder VM
  hosts: image-builder
  become: yes
  tasks:
    - name: Build rfe-ostree
      include_role:
        name: build-rpm-ostree
