- name: Generate In-Memory Inventory of OpenShift VMs
  hosts: localhost
  roles:
    - role: openshift-image-builder-imi
      tags: openshift-image-builder-imi

- hosts: image-builder
  become: yes
  tasks:
    - name: Download rpm-ostree tar
      include_role:
        name: content-download-upload
        tasks_from: download-rfe-rpm-ostree.yaml

- hosts: localhost
  vars:
    nexus_credentials_secret_name: nexus-rfe-credentials
    nexus_rfe_tarball_repository: rfe-tarballs
  tasks:
    - name: Get Nexus Credentials
      community.kubernetes.k8s_info:
        api_key: "{{ lookup('file', '/var/run/secrets/kubernetes.io/serviceaccount/token') }}"
        ca_cert: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        host: https://kubernetes.default.svc
        kind: Secret
        namespace: rfe
        name: "{{ nexus_credentials_secret_name }}"
        validate_certs: yes
      failed_when: nexus_secret.resources | length != 1
      register: nexus_secret

    - name: Set Nexus Credentials
      set_fact:
        nexus_username: "{{ nexus_secret.resources[0].data.username | b64decode }}"
        nexus_password: "{{ nexus_secret.resources[0].data.password | b64decode }}"
      no_log: true

    - name: Upload to Nexus and HTTPD
      include_role:
        name: content-download-upload
        tasks_from: upload-rfe-artifact.yaml
      vars:
        file_to_upload: "{{ hostvars['image-builder']['rfe_downloaded_file_path'] }}"
        nexus_repository: "{{ nexus_rfe_tarball_repository }}"
